server:
  port: 8086


##-------------------------------------------- notify bot telegram --------------------------------------------##
notify-telegram-bot:
  api:
    url: http://localhost:8087/
    endpoints:
      notify-order: api/v1/notify/order
