server:
  port: 8088
  ssl:
    key-store: src/main/resources/telegram-keystore.p12
    key-store-password: changeit
    key-store-type: pkcs12
    enabled: false

storage:
  dir-path: C:\Users\Dell\Desktop\shop\storage/
  url: https://foxshop.zapto.org/api/v1/download/

##---------------------------------------------------- mongo db ----------------------------------------------------##
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: com_fox_shop_storage


##---------------------------------------------------- telegram ----------------------------------------------------##
telegram:
  api:
    endpoints:
      get-file: getFile
      set-my-commands: setMyCommands
      send-message: sendMessage
      send-photo: sendPhoto
      send-animation: sendAnimation
      send-video: sendVideo
      send-media-group: sendMediaGroup
      delete-message: deleteMessage
  bot:
    notify:
      chat-id: 308041200
      base-url: https://api.telegram.org/bot5083514865:AAHkYcbckXeWTH-7km2XGugflY-YiB2ONSU/
    shop:
      #chat-id: 398656915  # Victor
      chat-id: 308041200  # mine
      base-url: https://api.telegram.org/bot2139497010:AAHpAiEGec8vECZhUmJjSoxVY2fki0bnwBE/

##---------------------------------------------------- base ----------------------------------------------------##
base:
  api:
    url:
    endpoints:


