server:
  port: 8088
  ssl:
    key-store: src/main/resources/keystore-telegram.p12
    key-store-password: password
    key-store-type: pkcs12

storage:
  dir-path: C:/Users/User/Desktop/java_projects/shop/storage/
  url: https://192.168.1.1:8088/api/v1/download/

##---------------------------------------------------- mongo db ----------------------------------------------------##
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: com_fox_shop_bot

telegram:
  api:
    endpoints:
      get-file: getFile
      set-my-commands: setMyCommands
      send-message: sendMessage
      send-photo: sendPhoto
      send-animation: sendAnimation
      send-video: sendVideo
      send-media-group: sendMediaGroup
      delete-message: deleteMessage
  bot:
    notify:
      chat-id: 308041200
      base-url: https://api.telegram.org/bot5083514865:AAEm5VFegVNbDyqc5VZFjKj5ndLOTnoxY88/
    shop:
      #chat-id: 398656915  # Victor
      chat-id: 308041200  # mine
      base-url: https://api.telegram.org/bot5083514865:AAEm5VFegVNbDyqc5VZFjKj5ndLOTnoxY88/


